### PR TITLE
Added methods for Edit and Delete. Along with an Edit View.

### PR DESCRIPTION
**Pull request by GuillermoVenturaReyes**
Added methods for Edit and Delete, along with Edit view w/ Joe Stalnaker

### CODE REVIEW

**Review by kaurrevature — CHANGES_REQUESTED** [review]
Kindly add the missing methods in the REST API and test both with integration

**Comment by GuillermoVenturaReyes** [comment]
I think I added the correct methods.

**Review by GuillermoVenturaReyes — COMMENTED** [review]
I believe I added the required methods

**Review by kaurrevature — COMMENTED** [review]
Good Work!

**Review by kaurrevature — APPROVED** [review]

**Pull request merged**
